require "hzln3t.options"
require "hzln3t.keymaps"
require "hzln3t.plugins"
require "hzln3t.colorscheme"
require "hzln3t.telescope"
require "hzln3t.git"
require "hzln3t.treesitter"
require "hzln3t.autopairs"
require "hzln3t.autotags"
require "hzln3t.comment"
require "hzln3t.bufferline"
require "hzln3t.lualine"

